### ISSUE TITLE
Buffers are intermittently converted into BigInt data, rather than strings

### ISSUE THREAD

**Issue by Vectorrent** [kylebarron/parquet-wasm#568] opened 2024-07-15 23:11 UTC
## Versions
apache-arrow: ^16.1.0
parquet-wasm: ^0.6.1
Node.js: v18.20.3
Chromium: 126.0.6478.126

## Problem
I am building a sampler class that fetches shards from the [Cosmopedia](https://huggingface.co/datasets/HuggingFaceTB/cosmopedia) dataset, and converts them into batches of training data, used for training language models in the browser. In general, `parquet-wasm` is working very well here, and I appreciate your work!

However, I'm running into a strange issue. At first-run of the following script, my code will pull from a remote shard, create batches, return them as strings, etc. Everything works correctly. Periodically, I will pull a new shard, and overwrite the previous buffer. In general, this works.

However, seemingly at-random, `column.get(rowIdx)` will start returning BigInt numbers like `173n`, rather than strings. I have no idea why this is happening, but it is very consistent, if you run the following code for just a few minutes:
```js
import * as arrow from 'apache-arrow'
import wasmInit, { readParquet } from 'parquet-wasm'

function randomBetween(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}

function randomValueFromArray(array) {
    const randomIndex = Math.floor(Math.random() * array.length)
    return array[randomIndex]
}

function generatePaddedNumbers(start, end, totalDigits) {
    const numbers = []
    for (let i = start; i <= end; i++) {
        numbers.push(String(i).padStart(totalDigits, '0'))
    }
    return numbers
}

export default class CosmopediaDataset {
    constructor(config) {
        this.dataset = 'HuggingFaceTB/cosmopedia'
        this.slices = [
            { slice: 'auto_math_text', shards: 18 },
            { slice: 'khanacademy', shards: 1 },
            { slice: 'openstax', shards: 2 },
            { slice: 'stanford', shards: 13 },
            { slice: 'stories', shards: 43 },
            { slice: 'web_samples_v1', shards: 139 },
            { slice: 'web_samples_v2', shards: 118 },
            { slice: 'wikihow', shards: 2 }
        ]
        this.split = 'train'
        this.delimiter = '\n\n'
        this.eosToken = '<|eos|>'
        this.cacheSize = 20000
        this.cachedText = ''
        this.cycleShardInterval = 10000 // batches
        this.batches = 0
    }

    async init() {
        const isBrowser =
            (typeof self !== 'undefined' &&
                typeof self.importScripts === 'function') ||
            typeof window !== 'undefined'
        if (isBrowser) await wasmInit()
        await this.fetchRandomShard()
    }

    async fetchRandomShard() {
        const { slice, shards } = this.getWeightedRandomSlice(this.slices)
        const shardIndices = generatePaddedNumbers(0, shards, 5)
        const numShards = shardIndices.slice(-1)
        const allShards = shardIndices.slice(0, -1)
        const shard = randomValueFromArray(allShards)
        console.log('fetching shard:', `${shard}/${numShards}`, 'slice:', slice)
        const path = `data/${slice}/${this.split}-${shard}-of-${numShards}.parquet`
        this.url = `https://huggingface.co/datasets/${this.dataset}/resolve/main/${path}`
        console.log(this.url)
        try {
            const response = await fetch(this.url)
            this.buffer = new Uint8Array(await response.arrayBuffer())
            this.moveDataIntoTable()
            console.log('moved shard to table:', shard)
        } catch (err) {
            console.warn(
                `Failed to fetch shard (${shard}) from HuggingFace! We will continue using the old shard for now...`
            )
        }
    }

    moveDataIntoTable() {
        // Read Parquet buffer to Arrow Table
        const arrowWasmTable = readParquet(this.buffer)
        // Convert to JS Arrow Table
        this.table = arrow.tableFromIPC(arrowWasmTable.intoIPCStream())
    }

    getWeightedRandomSlice(slices) {
        // Calculate the total number of shards
        const totalShards = slices.reduce((sum, slice) => sum + slice.shards, 0)

        // Generate a random number between 0 and the total number of shards
        const randomShard = Math.floor(Math.random() * totalShards)

        // Find the slice that corresponds to the random shard
        let accumulatedShards = 0
        for (const slice of slices) {
            accumulatedShards += slice.shards
            if (randomShard < accumulatedShards) {
                return slice
            }
        }
    }

    viewSchema() {
        console.log(table.schema.toString())
    }

    loadSchema(array = [{ prompt: 'INPUT: ' }, { text: 'OUTPUT: ' }]) {
        this.schema = []
        array.map((obj) => {
            Object.entries(obj).forEach(([key, value]) => {
                const idx = this.table.schema.fields.findIndex(
                    (field) => field.name === key
                )
                console.assert(
                    idx !== -1,
                    `the key of ${key} does not exist in this dataset`
                )
                this.schema.push({ idx, value })
            })
        })
    }

    fillCache() {
        while (this.cachedText.length < this.cacheSize) {
            let shouldSkip = false
            let batchIdx = randomBetween(0, this.table.batches.length - 1)

            const text = []

            let rowIdx = null
            for (const obj of this.schema) {
                const column = this.table.batches[batchIdx].getChildAt(obj.idx)
                if (rowIdx === null) {
                    rowIdx = randomBetween(0, column.length - 1)
                }
                const prefix = obj.value
                const data = column.get(rowIdx)
                // Some 'data' values appear to be random integers, with no other information. So, we
                // try to skip them here.
                if (/^-?\d+$/.test(data)) {
                    console.log(this.url)
                    console.log(data)
                    console.log('prefix was:', prefix)
                    console.log('batchIdx was:', batchIdx)
                    console.log('rowIdx was:', rowIdx)
                    console.log('data was:', data)
                    shouldSkip = true
                    throw 'data was invalid' // this is temporary, for debugging, so we don't spam the terminal
                }
                text.push(prefix + data)
            }
            if (shouldSkip) continue
            this.cachedText += text.join(this.delimiter) + this.eosToken
        }
    }

    async getSample(size = 512) {
        this.batches++
        if (this.batches % this.cycleShardInterval === 0) {
            await this.fetchRandomShard()
        }
        this.fillCache()
        const sample = this.cachedText.slice(0, size)
        this.cachedText = this.cachedText.slice(size)
        return sample
    }
}

const numIterations = 1_000_000_000_000
async function main() {
    const sampler = new CosmopediaDataset()
    await sampler.init()
    sampler.loadSchema([{ prompt: 'INPUT: ' }, { text: 'OUTPUT: ' }])
    for (let i = 0; i < numIterations; i++) {
        if (i % 1000 === 0) console.log('iterations:', i)
        await sampler.getSample()
    }
}

main()
```
I'm fairly certain that I'm doing something wrong here, but as of yet - I've not been able to identify what.

I can confirm that this is not an issue with specific shards. I am not able to reproduce failing shards, because there is nothing wrong with the training data itself.

For now, I can handle the problem by just downloading/loading shards repeatedly, until the issue eventually resolves itself (temporarily). A more-reliable solution would be better though.

Any ideas about what I can do here? I would greatly appreciate any help you could provide.

**Comment by kylebarron** [comment] 2024-07-16 02:11
I would assume that this is a bug in Arrow JS, not in parquet-wasm. 

> However, seemingly at-random, column.get(rowIdx) will start returning BigInt numbers like 173n, rather than strings

if you decode 173 to ascii, is that the character you expected for that row? Can you compare against another parquet/arrow implementation, like in Python?

**Comment by Vectorrent** [comment] 2024-07-16 02:38
I don't have any Python versions of this code readily available for testing, but I can confirm that Huggingface's `datasets` library works fine with these Parquet files. I can also confirm that the async API for `parquet-wasm` has the exact same problem, intermittently.

I'm not entirely sure if these BigInt numbers can actually be decoded as ASCII? Typically, `column.get(rowIdx)` will return a giant block of text - not a single character.

**Comment by kylebarron** [comment] 2024-07-16 03:10
> I can also confirm that the async API for `parquet-wasm` has the exact same problem, intermittently.

Without any further information, it's likely that the Rust code (i.e. parquet-wasm) is working correctly in both cases, but that Arrow JS has some bug. The Rust Parquet library is quite stable and used by some large database projects.

Do you have a URL and row index to a specific file that has this issue?

**Comment by Vectorrent** [comment] 2024-07-16 03:19
Thanks, this gives me something to work with. Perhaps I'll reach out to the Arrow team.

I don't have a specific row index, because the issue is transient. This problem can affect any row (actually, when it happens, it affects EVERY row and batch, in the entire shard). 

If I restart the script, that shard, batch and row will work just fine. The data isn't the problem (I don't think); it's something related to the conversion process.

**Comment by kylebarron** [comment] 2024-07-16 14:44
Maybe you could let that script run until you hit a bigint error; and at that point catch the error and write out to a file the Arrow stream buffer and the given row? I'd suggest you write to a file the original Arrow IPC stream generated by parquet-wasm, before Arrow-js even touches it, to isolate whether the error is in parquet-wasm or arrow-js

**Comment by Vectorrent** [comment] 2024-07-17 07:05
Perhaps I've misunderstood your suggestion, but I did give this a try. If I write the Arrow stream buffer to a file (when this problem occurs), I receive a ~400MB text file in some kind of binary-encoded format, which is a mixture of nonsense and text data. Here's a snippet of that output:
![image](https://github.com/user-attachments/assets/5007c270-e1d9-4697-8a24-e624ba014364)
This does seem to indicate that both of the following steps were <probably> successful:
```js
// Read Parquet buffer to Arrow Table
this.arrowWasmTable = readParquet(this.buffer)
// Get the Arrow stream buffer
this.arrowStreamBuffer = this.arrowWasmTable.intoIPCStream()
```
Then, the bug occurs here:
```js
// Convert to JS Arrow Table
this.table = tableFromIPC(this.arrowStreamBuffer)
```
This is just my interpretation. Regardless, when `column.get(rowIdx)` begins to receive BigInt data - ALL data (in every batch and row) is BigInt data. The only way to fix it is to keep re-loading shards, until it eventually works.

Were you ever able to reproduce my issue? Here is some updated, simplified reproduction code, which also implements the buffer-writes to disk:
```js
import fs from 'fs'
import { tableFromIPC } from 'apache-arrow'
import { readParquet } from 'parquet-wasm'

class CosmopediaDataset {
    constructor() {
        this.dataset = 'HuggingFaceTB/cosmopedia'
        this.slices = [
            { slice: 'auto_math_text', shards: 18 },
            { slice: 'khanacademy', shards: 1 },
            { slice: 'openstax', shards: 2 },
            { slice: 'stanford', shards: 13 },
            { slice: 'stories', shards: 43 },
            { slice: 'web_samples_v1', shards: 139 },
            { slice: 'web_samples_v2', shards: 118 },
            { slice: 'wikihow', shards: 2 }
        ]
        this.split = 'train'
        this.delimiter = '\n\n'
        this.eosToken = '<|eos|>'
        this.cacheSize = 20000
        this.cachedText = ''
        this.cycleShardInterval = 10000 // batches
        this.batches = 0
        this.arrowWasmTable = null
    }

    async init() {
        await this.fetchRandomShard()
    }

    async fetchRandomShard() {
        const { slice, shards } = randomValueFromArray(this.slices)
        const shardIndices = generatePaddedNumbers(0, shards, 5)
        const numShards = shardIndices.slice(-1)
        const allShards = shardIndices.slice(0, -1)
        const shard = randomValueFromArray(allShards)
        console.log('fetching shard:', `${shard}/${numShards}`, 'slice:', slice)
        const path = `data/${slice}/${this.split}-${shard}-of-${numShards}.parquet`
        this.url = `https://huggingface.co/datasets/${this.dataset}/resolve/main/${path}`
        console.log(this.url)
        const response = await fetch(this.url)
        this.buffer = new Uint8Array(await response.arrayBuffer())
        this.moveDataIntoTable()
        console.log('moved shard to table:', shard)
    }

    moveDataIntoTable() {
        // Read Parquet buffer to Arrow Table
        this.arrowWasmTable = readParquet(this.buffer)
        // Get the Arrow stream buffer
        this.arrowStreamBuffer = this.arrowWasmTable.intoIPCStream()
        // Convert to JS Arrow Table
        this.table = tableFromIPC(this.arrowStreamBuffer)
    }

    loadSchema(array = [{ prompt: 'INPUT: ' }, { text: 'OUTPUT: ' }]) {
        this.schema = []
        array.map((obj) => {
            Object.entries(obj).forEach(([key, value]) => {
                const idx = this.table.schema.fields.findIndex(
                    (field) => field.name === key
                )
                this.schema.push({ idx, value })
            })
        })
    }

    async fillCache() {
        while (this.cachedText.length < this.cacheSize) {
            let shouldSkip = false
            let batchIdx = randomBetween(0, this.table.batches.length - 1)

            const text = []

            let rowIdx = null
            for (const obj of this.schema) {
                let column = this.table.batches[batchIdx].getChildAt(obj.idx)
                if (rowIdx === null) {
                    rowIdx = randomBetween(0, column.length - 1)
                }
                const prefix = obj.value
                const data = column.get(rowIdx)
                // Some 'data' values appear to be random integers, with no other information.
                // We handle that here.
                if (/^-?\d+$/.test(data)) {
                    console.log(
                        'FAILED TO PARSE SHARD: Received a BigInt instead of text.'
                    )
                    console.log(data)
                    console.log('prefix was:', prefix)
                    console.log('batchIdx was:', batchIdx)
                    console.log('rowIdx was:', rowIdx)
                    console.log('data was:', data)
                    shouldSkip = true
                    fs.writeFileSync(
                        './arrowStreamBuffer.txt',
                        this.arrowStreamBuffer
                    )
                    await this.fetchRandomShard()
                }
                text.push(prefix + data)
            }
            if (shouldSkip) continue
            this.cachedText += text.join(this.delimiter) + this.eosToken
        }
    }

    async getSample(size = 512) {
        this.batches++
        if (this.batches % this.cycleShardInterval === 0) {
            await this.fetchRandomShard()
        }
        await this.fillCache()
        const sample = this.cachedText.slice(0, size)
        this.cachedText = this.cachedText.slice(size)
        return sample
    }
}

function randomBetween(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}

function randomValueFromArray(array) {
    const randomIndex = Math.floor(Math.random() * array.length)
    return array[randomIndex]
}

function generatePaddedNumbers(start, end, totalDigits) {
    const numbers = []
    for (let i = start; i <= end; i++) {
        numbers.push(String(i).padStart(totalDigits, '0'))
    }
    return numbers
}

const numIterations = 1_000_000_000_000
async function main() {
    const sampler = new CosmopediaDataset()
    await sampler.init()
    sampler.loadSchema([{ prompt: 'INPUT: ' }, { text: 'OUTPUT: ' }])
    for (let i = 0; i < numIterations; i++) {
        if (i % 1000 === 0) console.log('iterations:', i)
        await sampler.getSample()
    }
}

main()
```

**Comment by kylebarron** [comment] 2024-07-17 16:01
> I receive a ~400MB text file in some kind of binary-encoded format, which is a mixture of nonsense and text data

This is the Arrow IPC format. The text data you're seeing is embedded strings inside the file. The "nonsense" is the binary data of other non-text columns. You should be able to write that to a file and open it with any Arrow implementation in any language.

I'm really busy right now and don't have time to go down a rabbit hole. You should try to isolate parquet-wasm from arrow-js. Write that IPC buffer to a file and try to open it with some other Arrow implementation. If that works, then the problem is with Arrow JS, not parquet-wasm.

E.g. with pyarrow it's a [few lines of code I think:](https://arrow.apache.org/docs/python/generated/pyarrow.ipc.open_stream.html)

```py
import pyarrow as pa

with pa.ipc.open_stream(arrow_file_on_disk) as reader:
	table = reader.read_all()
```

**Comment by Vectorrent** [comment] 2024-07-19 02:25
Thank you, this was very helpful. I wrote a small script to test this buffer in PyArrow - and it appears to work:
```
(venv) [crow@crow-pc ode]$ python pyarrowtesting.py 
Table schema: text: string
prompt: string
text_token_length: int64
seed_data: string
format: string
audience: string
-- schema metadata --
huggingface: '{"info": {"features": {"text": {"dtype": "string", "_type":' + 272
Number of columns: 6
Number of rows: 116116

First 5 rows of data:
                                                text                                             prompt  text_token_length      seed_data              format        audience
0   A few months ago, I came across a post in r/2...  Write a real-life story shared by someone in a...                984      ultrachat        story_reddit         general
1   The hum of the airplane engines droned softly...  Write a compelling story related to the follow...                561      ultrachat      story_morality         general
2   Once upon a time, in a bustling city lived tw...  Write an educational story (3-5 paragraphs) ta...                436  openhermes2.5      story_children  young_children
3   Dr. Sarah leaned back in her chair, rubbing h...  Write a compelling story related to the follow...                651      ultrachat      story_morality         general
4   In the bustling city of Colombo, Sri Lanka, t...  Write a story that explores a situation slight...                877      ultrachat  story_life_lessons         general
```
So yes, that does appear to confirm that the buffer from `parquet-wasm` is not the problem; it has something to do with the `apache-arrow` conversion. I will move this troubleshooting into [this issue](https://github.com/apache/arrow/issues/43275), then.

For posterity, here is the `pyarrow` script that works fine - even when `apache-arrow` does not:
```py
import pyarrow as pa
import pyarrow.ipc as ipc

def main():
    # Replace 'path/to/your/arrow_file.arrow' with the actual path to your Arrow file
    arrow_file_on_disk = './arrowStreamBuffer.txt'

    try:
        # Open the Arrow file
        with ipc.open_stream(arrow_file_on_disk) as reader:
            # Read all the data into a table
            table = reader.read_all()

        # Print information about the table
        print(f"Table schema: {table.schema}")
        print(f"Number of columns: {table.num_columns}")
        print(f"Number of rows: {table.num_rows}")

        # Print the first 5 rows of the table
        print("\nFirst 5 rows of data:")
        print(table.to_pandas().head())

    except FileNotFoundError:
        print(f"Error: The file '{arrow_file_on_disk}' was not found.")
    except pa.lib.ArrowInvalid:
        print(f"Error: '{arrow_file_on_disk}' is not a valid Arrow file or is corrupted.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    main()
```

**Comment by kylebarron** [comment] 2024-07-20 16:54
Ok great, then it sounds like I can close this issue?

**Closed by kylebarron** 2024-07-20 16:54 UTC
