### ISSUE TITLE
Out-of-memory when reading big-ish parquet files

### ISSUE THREAD

**Issue by zenazn** [kylebarron/parquet-wasm#238] opened 2022-10-19 23:31 UTC
I have a use case where I'd like to be able to access a big-ish parquet file in a browser context using `parquet-wasm`. It's ~80MB compressed, ~1.5MM rows, and ~50 columns. Some of the columns contain strings that make up an appreciable fraction of the data size, and they're unfortunately not stored as categorical data. I unfortunately can't share the original dataset (it contains customer data), but I can likely construct a demo parquet file if that's helpful to you.

The problem I'm having is somewhat amusing: `parquet-wasm` (arrow2) runs out of memory writing the arrow IPC format to its own memory, prior to it returning that IPC data to javascript. Unfortunately, `pandas` (the writer of this data) doesn't consider this to be an especially large dataset, and writes the entire thing as a single row group, which I think means the new streaming APIs won't help me (though in fairness I haven't tried).

Is there a good solution or workaround here? Or am I just out of luck?

**Comment by kylebarron** [comment] 2022-10-20 02:03
> Unfortunately, `pandas` (the writer of this data) doesn't consider this to be an especially large dataset, and writes the entire thing as a single row group

Could be better documented, but if you're using pyarrow pandas [passes the kwargs](https://github.com/pandas-dev/pandas/blob/b5958ee1999e9aead1938c0bba2b674378807b3d/pandas/io/parquet.py#L123) to `pyarrow.parquet.write_table`. So you can [set `row_group_size`](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) as the number of rows per row group.

> runs out of memory writing the arrow IPC format to its own memory, prior to it returning that IPC data to javascript

The actual fix for this is to implement Arrow's C Data Interface across the wasm boundary (see [this blog post](https://observablehq.com/@kylebarron/zero-copy-apache-arrow-with-webassembly)). So we'd never need the copy into IPC memory and we'd get better space utilization with each column chunk potentially isolated in wasm memory space. This is implemented on the rust side with [`read_parquet_ffi`](https://github.com/kylebarron/parquet-wasm/blob/02431149e7e9b33e7912f046c6c76c02fffb1e8d/src/arrow2/wasm.rs#L55), but the issue is that Arrow JS needs to implement the C Data Interface as well to understand that. I started that in https://github.com/kylebarron/arrow-js-ffi; primitive types [pass basic tests](https://github.com/kylebarron/arrow-js-ffi/blob/eb4d1c0595dbef86f80b19500bafbf601728635a/tests/ffi.ts#L17) but otherwise it's pretty alpha code. PRs welcome if you try to go that route

**Comment by kylebarron** [comment] 2023-08-16 01:23
This should be fixed as much as possible in the latest release, with the addition of `readParquetFFI`

**Comment by kylebarron** [comment] 2023-08-16 01:24
Ref https://github.com/kylebarron/parquet-wasm/pull/287

**Closed by kylebarron** 2023-08-16 01:24 UTC
