### ISSUE TITLE
Fully empty file does not load

### ISSUE THREAD

**Issue by isaacbrodsky** [kylebarron/parquet-wasm#511] opened 2024-04-19 17:23 UTC
```python
import pandas as pd
pd.DataFrame().to_parquet('empty.parquet')
```

I tried to load this in parquet-wasm and I got "unreachable executed". Having zero rows but some columns did work.

**Comment by kylebarron** [comment] 2024-04-21 19:44
In the latest main I can't reproduce this. Using the test case added in https://github.com/kylebarron/parquet-wasm/pull/512 I can see the table schema as such:

```
stdout | tests/js/index.test.ts > reads empty file
empty table schema Schema {
  fields: [],
  metadata: Map(1) {
    'pandas' => '{"index_columns": [{"kind": "range", "name": null, "start": 0, "stop": 0, "step": 1}], "column_indexes": [{"name": null, "field_name": null, "pandas_type": "int64", "numpy_type": "int64", "metadata": null}], "columns": [], "creator": {"library": "pyarrow", "version": "13.0.0"}, "pandas_version": "2.1.1"}'
  },
  dictionaries: Map(0) {},
  metadataVersion: 4
}
```

**Comment by kylebarron** [comment] 2024-04-21 19:46
Based on https://github.com/kylebarron/parquet-wasm/pull/512 I'll close this, but feel free to reopen if you have another reproducible example

**Closed** 2024-04-21 19:47 UTC

**Comment by isaacbrodsky** [comment] 2024-04-21 20:05
Interesting! I'll keep on the lookout for it. Thanks for adding the test.

**Comment by kylebarron** [comment] 2024-04-29 22:36
Great to hear
